version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/userdb
    depends_on:
      - mongodb
    volumes:
      - .:/src
    command: gunicorn --bind 0.0.0.0:5000 "src:create_app()"

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
